### ISSUE TITLE
access exisiting plist?

### ISSUE THREAD

**Issue by sirvon** [monyschuk/PropertyList#1]
new to swift/ios dev....
using this lib how can I access an existing plist?

**Comment by monyschuk** [comment]
You'll want to read the Plist into an NSData then use the class func plistFromData(...)

**Comment by monyschuk** [comment]
More step-by-step:
1/ use NSBundle to get the path or URL of the .plist file
2/ use NSData(filename:...) or NSData(URL:) to load the plist data
3/ use the class function on Plist to create a Plist from the contents of your data object
